games:
  "FireRed/LeafGreen":
    Chansey:
      catch_rate: 30
      escape_rate: 125
    Doduo:
      catch_rate: 190
      escape_rate: 50
    Dragonair:
      catch_rate: 45
      escape_rate: 125
    Dratini:
      catch_rate: 45
      escape_rate: 100
    Exeggcute:
      catch_rate: 90
      escape_rate: 75
    Goldeen:
      catch_rate: 225
      escape_rate: 50
    Kangaskhan:
      catch_rate: 45
      escape_rate: 125
    Magikarp:
      catch_rate: 255
      escape_rate: 25
    Nidoran_F:
      catch_rate: 235
      escape_rate: 50
    Nidoran_M:
      catch_rate: 235
      escape_rate: 50
    Nidorina:
      catch_rate: 120
      escape_rate: 75
    Nidorino:
      catch_rate: 120
      escape_rate: 75
    Paras:
      catch_rate: 190
      escape_rate: 50
    Parasect:
      catch_rate: 75
      escape_rate: 75
    Pinsir:
      catch_rate: 45
      escape_rate: 125
    Poliwag:
      catch_rate: 255
      escape_rate: 50
    Psyduck:
      catch_rate: 190
      escape_rate: 50
    Rhyhorn:
      catch_rate: 120
      escape_rate: 75
    Scyther:
      catch_rate: 45
      escape_rate: 125
    Seaking:
      catch_rate: 60
      escape_rate: 75
    Slowpoke:
      catch_rate: 190
      escape_rate: 50
    Tauros:
      catch_rate: 45
      escape_rate: 125
    Venonat:
      catch_rate: 190
      escape_rate: 50
    Venomoth:
      catch_rate: 75
      escape_rate: 75
